from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
import googlemaps
import os


CHAT_MODEL = ChatOpenAI(
    openai_api_key=os.getenv("OPENAI_API_KEY"),
    temperature=0, 
    model="gpt-3.5-turbo"
)
EMBED_MODEL = OpenAIEmbeddings(
    model="text-embedding-3-large",
    dimensions=1024,
    openai_api_key=os.getenv('OPENAI_API_KEY')
)
EMBEDDINGS_COLLECTION_NAME = "chunked_reviews_openai"
EMBEDDINGS_INDEX= 'chunked_reviews_openai_index'
NUM_CANDIDATES=50
NEIGHBORHOOD_DISTANCE_THRESHOLD = 0.5   # in miles

GMAPS_CLIENT = googlemaps.Client(key=os.environ.get('GOOGLE_API_KEY'))

MANHATTAN = [
    "alphabet city",
    "battery park city",
    "bloomingdale district",
    "bowery",
    "carnegie hill",
    "central park",
    "chelsea",
    "chinatown",
    "civic center",
    "east harlem",
    "east village",
    "financial district",
    "flatiron district",
    "fort george",
    "garment district",
    "governors island",
    "gramercy",
    "greenwich village",
    "hamilton heights",
    "harlem",
    "hell's kitchen",
    "the highline",
    "hudson heights",
    "hudson square",
    "hudson yards",
    "inwood",
    "kips bay",
    "lenox hill",
    "lincoln square",
    "little italy",
    "lower east side",
    "manhattan valley",
    "manhattanville",
    "marble hill",
    "meatpacking district",
    "metropolitan hill",
    "midtown",
    "midtown east",
    "midtown south",
    "morningside heights",
    "murray hill",
    "noho",
    "nolita",
    "nomad",
    "randall's island",
    "roosevelt island",
    "rose hill",
    "soho",
    "south street seaport",
    "spanish harlem",
    "stuyvesant town",
    "sugar hill",
    "sutton place",
    "theater district",
    "tribeca",
    "tudor city",
    "turtle bay",
    "two bridges",
    "upper east side",
    "upper west side",
    "washington heights",
    "west village",
    "world trade center",
    "yorkville"
]

BROOKLYN = [
    "albemarle",
    "bath beach",
    "bay ridge",
    "bedford-stuyvesant",
    "bensonhurst",
    "bergen beach",
    "boerum hill",
    "borough park",
    "brighton beach",
    "brooklyn heights",
    "brooklyn navy yard",
    "brownsville",
    "bushwick",
    "canarsie",
    "carroll gardens",
    "city line",
    "clinton hill",
    "cobble hill",
    "columbia street waterfront",
    "coney island",
    "crown heights",
    "cypress hills",
    "dahill",
    "downtown brooklyn",
    "dumbo",
    "dyker beach park",
    "dyker heights",
    "east flatbush",
    "east new york",
    "east williamsburg",
    "erasmus",
    "farragut",
    "flatbush",
    "flatlands",
    "fort greene",
    "fort hamilton",
    "georgetown",
    "gerritsen beach",
    "gowanus",
    "gravesend",
    "greenpoint",
    "greenwood cemetery",
    "greenwood heights",
    "highland park",
    "homecrest",
    "kensington",
    "los sures - southside",
    "manhattan beach",
    "madison",
    "mapleton",
    "marine park",
    "midwood",
    "midwood park",
    "mill basin",
    "new lots",
    "northside",
    "ocean hill",
    "paedergat",
    "park slope",
    "parkville",
    "prospect heights",
    "prospect-lefferts gardens",
    "prospect park",
    "prospect park south",
    "red hook",
    "remsen village",
    "seagate",
    "sheepshead bay",
    "south slope",
    "south williamsburg",
    "starrett city",
    "stuyvesant heights",
    "sunset park",
    "victorian flatbush",
    "vinegar hill",
    "williamsburg",
    "windsor terrace",
    "wingate"
]

QUEENS = [
    'alley pond park',
    'arverne',
    'astoria',
    'astoria heights',
    'auburndale',
    'bay terrace',
    'bayside',
    'bayside hills',
    'bayswater',
    'beechhurst',
    'bellaire',
    'belle harbor',
    'bellerose',
    'bellerose manor',
    'breezy point',
    'briarwood',
    'broad channel',
    'broadway-flushing',
    'brookville',
    'brookville park',
    'cambria heights',
    'college point',
    'corona',
    'cunningham park',
    'ditmars-steinway',
    'douglas manor',
    'douglaston',
    'downtown flushing',
    'east elmhurst',
    'edgemere',
    'elmhurst',
    'far rockaway',
    'floral park',
    'flushing heights',
    'flushing meadows corona park',
    'forest hills',
    'forest hills gardens',
    'forest park',
    'fort tilden-jacob riis parks',
    'fresh meadows',
    'glen oaks',
    'glendale',
    'hamilton beach',
    'hillcrest',
    'the hole',
    'hollis',
    'hollis hills',
    'holliswood',
    'howard beach',
    "hunter's point",
    'jackson heights',
    'jamaica',
    'jamaica center',
    'jamaica estates',
    'jamaica hills',
    'kew gardens',
    'kew gardens hills',
    'kissena',
    'kissena park',
    'laurelton',
    'linden hill',
    'lindenwood',
    'little neck',
    'locust manor',
    'long island city',
    'malba',
    'maspeth',
    'meadowmere',
    'middle village',
    'murray hill',
    'neponsit',
    'new hyde park',
    'north corona',
    'oakland gardens',
    'old howard beach',
    'ozone park',
    'pomonok',
    'queens village',
    'queensboro hill',
    'rego park',
    'richmond hill',
    'richmond hill east',
    'ridgewood',
    'rochdale',
    'rockaway beach',
    'rockaway park',
    'rosedale',
    'roxbury',
    'south jamaica',
    'south ozone park',
    'south richmond hill',
    'springfield gardens',
    'st. albans',
    'sunnyside',
    'utopia',
    'whitestone',
    'willets point',
    'woodhaven',
    'woodside'
 ]

BRONX = [
    'allerton',
    'baychester',
    'bedford park',
    'belmont',
    'bronx park',
    'bronx river',
    'bronxwood',
    'castle hill',
    'city island',
    'claremont',
    'claremont village',
    'clason point',
    'co-op city',
    'concourse',
    'concourse village',
    'country club',
    'crotona',
    'crotona park',
    'east tremont',
    'eastchester',
    'eastchester bay',
    'edenwald',
    'fieldston',
    'fordham heights',
    'fordham manor',
    'foxhurst',
    'harding park',
    'highbridge',
    'hunts point',
    'indian village',
    'jerome park',
    'kingsbridge',
    'kingsbridge heights',
    'laconia',
    'locust point',
    'longwood',
    'melrose',
    'morris heights',
    'morris park',
    'morrisania',
    'mosholu',
    'mott haven',
    'mt. eden',
    'mt. hope',
    'north riverdale',
    'norwood',
    'olinville',
    'park of edgewater',
    'parkchester',
    'pelham bay',
    'pelham bay park',
    'pelham gardens',
    'pelham parkway',
    'port morris',
    'riverdale',
    'schuylerville',
    'silver beach',
    'soundview',
    'soundview park',
    'spuyten duyvil',
    'throggs neck',
    'unionport',
    'university heights',
    'van cortlandt park',
    'van cortlandt village',
    'van nest',
    'wakefield',
    'west farms',
    'westchester square',
    'williamsbridge',
    'woodlawn cemetery',
    'woodlawn heights'
 ]

STATEN_ISLAND = [
    'annadale',
    'arden heights',
    'arlington',
    'arrochar',
    'bay terrace',
    'bloomfield',
    'brighton heights',
    "bull's head",
    'castleton corners',
    'charleston',
    'clifton',
    'clove lakes park',
    'concord',
    'dongan hills',
    'dongan hills colony',
    'eltingville',
    'emerson hill',
    'fort wadsworth',
    'freshkills park',
    'graniteville',
    'grant city',
    'grasmere',
    'great kills',
    'great kills park',
    'grymes hill',
    'heartland village',
    'huguenot north',
    'huguenot south',
    'latourette park',
    'lighthouse hill',
    'manor heights',
    'mariners harbor',
    "meier's corners",
    'midland beach',
    'new brighton',
    'new dorp',
    'new dorp beach',
    'new springville',
    'oakwood',
    'old town',
    'park hill',
    'pleasant plains',
    'port richmond',
    "prince's bay",
    'randall manor',
    'richmond town',
    'richmond valley',
    'rosebank',
    'rossville',
    'sandy ground',
    'shore acres',
    'silver lake',
    'south beach',
    'st. george',
    'stapleton',
    'stapleton heights',
    'sunset hill',
    'sunnyside',
    'todt hill',
    'tompkinsville',
    'tottenville',
    'travis-chelsea',
    'west new brighton',
    'westerleigh',
    'willowbrook',
    'woodrow'
 ]